[build]
  command = "echo 'No build needed'"
  functions = "netlify-functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"
  directory = "netlify-functions"

[build.environment]
  NODE_VERSION = "18"
